### ISSUE TITLE
工作Tips

### ISSUE THREAD

**Issue by lssssya** [lssssya/blog#7]
#### 金融格式化
```js
(123123123).toLocaleString()
//   '123,123,123'
```

#### 判断时间是否在一段时间内
```js
const now = moment().locale('zh-cn').format('YYYY-MM-DD')
    this.weekList.forEach(item=>{
    if(moment(now).isBetween(item.startDate, item.endDate)){
         this.week = item.weekOrder
    }
})
```

#### 字符串 截取末尾固定字符
```js
order = order.substring(0, order.lastIndexOf('ending'))
```

#### 随机生成六位数字验证码
```js
const code = Math.floor(Math.random() * 1000000).toString().padStart(6, "0");
```

#### 维数组转一维数组
```js
const deepFlatten = arr => [].concat(...arr.map(v => (Array.isArray(v) ? deepFlatten(v) : v)));
deepFlatten([1, [2], [[3], 4], 5]); 
// [1,2,3,4,5]
```

#### flex 实现上面3个下面两个的排列
```css
.center {
  width: 60%;
  display: flex;
  flex-wrap: wrap;
  align-content: flex-start;
  div {
    flex: 0 0 33.333333%;
    width: 20%;
    height: 20px;
  }
}
```
